### ISSUE TITLE
Enable google authentication using firebase 

### ISSUE THREAD

**Issue by ameen-11** [ameen-11/Sensor_Hub#1]
When the user opens the app he must be promted to sign up or sign in using google depending on wether he is a new or registered user. If he is aldready signed in direct him to a dashboard with his details apperaing .

**Comment by AbhijithKumble** [comment]
In the dashboard what are the things that should be should be shown like age , gender etc

**Comment by ameen-11** [comment]
> In the dashboard what are the things that should be should be shown like age , gender etc

When the user signs in he must see a welcome message with his name ,  start and stop button for sensor . After that our analysis button . So in total 3 buttons on the dasboard as he signs in. On the top  app bar there must se a collasable side menu on the left and on the right a my profile link . On the collasable side menu just add links to 9 different dummy  pages .

**Comment by chamanchangappa03** [comment]
done
